[package]
name = "docker-rust-echo-server"
version = "0.1.0"
authors = ["Fraser Darwent <fraser@darwen.tf>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille = "3.0.0"
chrono = "0.4"
ctrlc = "3.1.4"